project: 
  type: website
  output-dir: _site
  
execute:
  freeze: true  # never re-execute computational content during project render, needed for .qmd and .rmd since quarto does not render .ipynb by default  
  
website: 
  page-navigation: true
  title: "Quarto Contributing Clinic" 
  site-url: https://openscapes.github.io/quarto-clinic/ 
  repo-url: https://github.com/Openscapes/quarto-clinic 
  repo-actions: [edit, source, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2024"
    
  sidebar:
    logo: "images/openscapes_hex.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://openscapes.org
        text: "Openscapes.org"
      - icon: github
        href: https://github.com/Openscapes/quarto-clinic
        text: "Quarto Contributing Clinic repo"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - href: explore.qmd
        text: Explore
      - section: workflows/index.qmd
        contents: 
          - href: workflows/jupyter.qmd
      - section: practice/index.qmd
        contents: 
          - practice/demo.qmd
          - practice/demo.ipynb
      - href: where-to-contribute.qmd
        text: Where to Contribute


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
