---
title: Next Steps
---

## Where to get help and learn more

### Quarto

-   <https://quarto.org/>
-   [A video to jumpstart your Quarto journey](https://quarto.org/docs/blog/posts/2023-05-15-get-started/), by Mine Çetinkaya-Rundel, May, 2023 (23 mins). *This is in RStudio IDE so will look different in the Hub.* Includes:
    -   Inserting [cross references](https://quarto.org/docs/authoring/cross-references.html) to tables and figures
    -   Adding a [citation](https://quarto.org/docs/visual-editor/technical.html#citations) from a DOI
    -   Seamlessly switching between output formats as well as creating [multi-format documents](https://quarto.org/docs/output-formats/html-multi-format.html)
    -   Customizing the [output location](https://quarto.org/docs/presentations/revealjs/#output-location) of code in presentations
    -   Creating a [website](https://quarto.org/docs/websites/) from scratch
-   [A Quarto tip a day](https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/), by Mine Çetinkaya-Rundel, July 2022

### GitHub

-   [Reviewing a pull request](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/workflow.html#review-a-pull-request) (with videos), in the NASA Earthdata Cloud Cookbook
-   [Tidyteam code review principles](https://code-review.tidyverse.org/), recommended by Andy Teucher
-   Openscapes lesson on [GitHub Strategies](https://openscapes.github.io/series/core-lessons/github/), the GitHub Clinic
-   Setting up Git credentials under [Tracking Changes](https://nasa-openscapes.github.io/2021-Cloud-Hackathon/tutorials/00_Setup.html#step-5.-tracking-changes-optional), in the 2021 Cloud Hackathon

## Where to contribute

We can use these skills to contribute to many Quarto websites and books.

-   [NASA Earthdata Cloud Cookbook](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/)
-   [NASA Openscapes](https://nasa-openscapes.github.io/)
    -   e.g. add a link to your slides or recording of a presentation
-   [Openscapes Approach Guide](https://openscapes.github.io/approach-guide/)

## Other example Quarto sites

-   [2021 NASA Cloud Hackathon](https://nasa-openscapes.github.io/2021-Cloud-Hackathon/)
-   [Openscapes Champions Lessons Series](https://openscapes.github.io/series)
-   [Faylab Lab Manual](https://thefaylab.github.io/lab-manual/)

See many more examples at the [Quarto gallery](https://quarto.org/docs/gallery/)!
